name: Deploy rust Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          cd server
          docker build -t ritchiegr8/secure-file-sharing .
      - name: Push Docker Image
        run: docker push ritchiegr8/secure-file-sharing:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ritchiegr8/secure-file-sharing:latest
      - name: Stop container if exists
        run: docker stop secure-file-sharing || true
      - name: Remove container if exists
        run: docker rm secure-file-sharing || true
      - name: Run docker container
        run: docker run -d -p 8000:8000 --name secure-file-sharing -e DATABASE_URL='${{ secrets.DATABASE_URL }}' -e JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}' -e JWT_MAX_AGE='${{ secrets.JWT_MAX_AGE }}' -e PORT='${{ secrets.PORT }}' -e FRONTEND_URL='${{ secrets.FRONTEND_URL }}' ritchiegr8/secure-file-sharing:latest
